on:
  push:
    branches:
      - main
  workflow_dispatch:
name: release-please
env:
  ACTION_NAME: action-terragrunt
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  release-please-release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          manifest-file: ".release-please-manifest.json"
          config-file: "release-please-config.json"
